language: ruby
rvm:
  - 2.2
notifications:
  email: false
before_script:
  - gem install awesome_bot
script:
  - awesome_bot *.md --allow-dupe --allow-redirect --white-list bitdeli,travis-ci,substanceproject,pan.baidu.com
